###############################################################################
## Business Problem: 
# Faults in a urban waste water treatment plant 
#(Data source: https://archive.ics.uci.edu/ml/datasets/Water+Treatment+Plant)
###############################################################################

## Business Objective: 
###############################################################################
# The objective is to classify the operational state of the plant in order to 
# predict faults through the state variables of the plant at each of the stages 
# of the treatment process.
###############################################################################

## Business Understanding: Clustering Problem
###############################################################################
# Required libraries
library(dplyr)
library(stringi)
library(caTools)
library(ggplot2)
library(tidyr)
library(corrplot)
library(scales)
library(gridExtra)
library(zoo)

#Loading  dataset # Total number of observations: 527 and attributes:38 
treatment <- read.delim("water-treatment.data.txt",sep = ',', stringsAsFactors = F,header = F)

# Structure of dataset
str(treatment)

# Get rid of first attribute i.e date,: 
treatment <- treatment[,-1]

# Basis on 38 attributes, we would want to segment the data based on the operational
# contidion of plants, but before going to use clustering analysis, we should initially
# reduce dataset dimensions i.e number of attributes. 

# Reduction of attributes basically helps in reducing the computational cost by using clustering technique

# So, let's first perform factor analysis on the given dataset: Water Treatment Data

############################ Factor Analysis ###################################

# Data Preparation: 

# Naming the attributes 
data_dictionary <- read.csv("Data_dictionary.csv")
colnames(treatment) <- data_dictionary[,2]

# Converting all the character attributes to the numeric type attributes
treatment[sapply(treatment, is.character)] <- lapply(treatment[sapply(treatment, is.character)], as.numeric)
# Warnings are introduced because of unknown character in the cell such as "?"

# Checking the total NAs in the dataset
sum(is.na(treatment)) 
# 591 missings are present

# Let's check the distribution of missings variable-wise

missing_values <- treatment %>%
  summarise_all(funs(sum(is.na(.))/n()))

missing_values <- gather(missing_values,key='feature',value = 'missing_percentage')

missing_values %>% ggplot(aes(x=reorder(feature,-missing_percentage),y=missing_percentage)) +
  geom_bar(stat = 'identity',fill='red') +
  coord_flip()

# Based on the plot, any attribute having more than 10% of data points missing is not eligible for imputation 
# hence it makes sense to compute and drop those variables

# Let's remove "RD_DBO_P" attribute from the dataset
treatment$RD_DBO_P <- NULL

# Summarise the datset

summary(treatment) # Mean and median of most of the attributes are nearly close to each other
#thus, it is better to replace all the attribute's NAs with their mean.
treatment <- na.aggregate(treatment)
sum(is.na(treatment))
##########################################################################

# Plot the correlations
corrplot(cor(treatment)) # Some attributes are highly correlated.

#Scaling the treatment data
treatment <- as.data.frame(scale(treatment))

# So indentifying the factor based on correlation matrix, works well on small dataset.
# But in large dataset such as water treatment(i.e.38 attributes), correlation matrix  doesn't 
# help in finding out the optimal factors. Thus, the PCA helps us identify the most important principle components

# Let's perfrom PCA on treatment dataset
treatment_pca <- princomp(treatment)

# Let's see the plot
# Based on the eigen values, we should consider the components which shows the ~ eigen value >1.

plot(treatment_pca)
# Total 7-8 principle components
screeplot(treatment_pca,type = 'line') 
# We would also require to perfrom cross validation as well to select the optimal components based on the eigen values, scree plot and cumulative variance.
# A scree plot shows the eigenvalues on the y-axis and the number of factors on the x-axis.
# It always displays a downward curve.The point where the slope of the curve is clearly leveling off 
# (the “elbow)indicates the number of factors that should be generated by the analysis.


#Factor Analysis at factors of 7.
fa1 <- factanal(treatment, factors = 7,rotation = "varimax")

fa1_load <- fa1$loadings

#Display Results
fa1_load

# Change attributes to factor variables 
treatment_factor <- factanal(treatment, factors = 7,rotation = "varimax",scores = "regression")

# Let's store it to dataset 
treatment_fat_dataset <- data.frame(treatment_factor$scores)
